export const demoVideos = [
  {
    id: 1,
    title: "Learn React in 30 Minutes",
    channel: "Programming with Mosh",
    thumbnail: "https://i.ytimg.com/vi/bMknfKXIFA8/hqdefault.jpg",
    views: "2.3M views",
    published: "2 years ago",
    category: "Learning",
  },
  {
    id: 2,
    title: "JavaScript Full Course",
    channel: "freeCodeCamp",
    thumbnail: "https://i.ytimg.com/vi/PkZNo7MFNFg/hqdefault.jpg",
    views: "5.1M views",
    published: "1 year ago",
    category: "Learning",
  },
  {
    id: 3,
    title: "CSS Crash Course",
    channel: "Traversy Media",
    thumbnail: "https://i.ytimg.com/vi/yfoY53QXEnI/hqdefault.jpg",
    views: "800K views",
    published: "8 months ago",
    category: "Learning",
  },
  {
    id: 4,
    title: "React Project Tutorial",
    channel: "JavaScript Mastery",
    thumbnail: "https://i.ytimg.com/vi/FHTbsZEJspU/hqdefault.jpg",
    views: "450K views",
    published: "5 months ago",
    category: "Learning",
  },
  {
    id: 5,
    title: "Node.js Crash Course",
    channel: "Traversy Media",
    thumbnail: "https://i.ytimg.com/vi/fBNz5xF-Kx4/hqdefault.jpg",
    views: "1.8M views",
    published: "3 years ago",
    category: "Learning",
  },
  {
    id: 6,
    title: "HTML Full Course",
    channel: "CodeWithHarry",
    thumbnail: "https://i.ytimg.com/vi/qz0aGYrrlhU/hqdefault.jpg",
    views: "3.7M views",
    published: "2 years ago",
    category: "Learning",
  },
];